branch-defaults:
  master:
    environment: null
global:
  application_name: reviewScrapperFlipkartFlask
  branch: master
  default_ec2_keyname: null
  default_platform: python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  plaform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application